/*
 * bbs-fw
 *
 * Copyright (C) Daniel Nilsson, 2022.
 *
 * Released under the GPL License, Version 3
 */
#ifndef _FWCONFIG_H_
#define _FWCONFIG_H_

// General configuration.

#define USE_FREEDOM_UNITS	0

#if defined(BBSHD)
	#define MAX_CURRENT_AMPS 30
#elif defined(BBS02)
	#define MAX_CURRENT_AMPS 25
#else
	#define MAX_CURRENT_AMPS 20
#endif

#define CURRENT_RAMP_AMPS_S 10
#define MAX_BATTERY_X100V 5880
#define LOW_CUT_OFF_V 42

#define USE_SPEED_SENSOR	1
#define USE_SHIFT_SENSOR	HAS_SHIFT_SENSOR_SUPPORT
#define USE_PUSH_WALK		1
#define USE_PRETENSION		0
#define PRETENSION_SPEED_CUTOFF_KPH 16
#define USE_TEMPERATURE_SENSOR	TEMPERATURE_SENSOR_CONTR
#define LIGHTS_MODE	LIGHTS_MODE_DEFAULT

#define WHEEL_CIRCUMFERENCE_MM 2268
#define SPEED_SENSOR_SIGNALS	1
#define MAX_SPEED_KPH	25

#define PAS_START_DELAY_PULSES	5
#define PAS_STOP_DELAY_X100S	20
#define PAS_KEEP_CURRENT_PERCENT	60
#define PAS_KEEP_CURRENT_CADENCE_RPM	40

#define THROTTLE_START_VOLTAGE_MV 1000
#define THROTTLE_END_VOLTAGE_MV 3600
#define THROTTLE_START_PERCENT 1
#define THROTTLE_GLOBAL_SPD_LIM_OPT THROTTLE_GLOBAL_SPEED_LIMIT_DISABLED
#define THROTTLE_GLOBAL_SPD_LIM_PERCENT	100

#define SHIFT_INTERRUPT_DURATION_MS	600
#define SHIFT_INTERRUPT_CURRENT_THRESHOLD_PERCENT	10

#define WALK_MODE_DATA_DISPLAY	WALK_MODE_DATA_SPEED
#define ASSIST_MODE_SELECT	ASSIST_MODE_SELECT_OFF
#define ASSIST_STARTUP_LEVEL	1

#define ASSIST_LEVEL_STANDARD_0_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_STANDARD_0_MAX_CADENCE_PERCENT	0
#define ASSIST_LEVEL_STANDARD_0_MAX_SPEED_PERCENT	0
#define ASSIST_LEVEL_STANDARD_0_MAX_THROTTLE_CURRENT_PERCENT	0
#define ASSIST_LEVEL_STANDARD_0_TARGET_CURRENT_PERCENT 0

#define ASSIST_LEVEL_STANDARD_1_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_STANDARD_1_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_STANDARD_1_MAX_SPEED_PERCENT	72
#define ASSIST_LEVEL_STANDARD_1_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_STANDARD_1_TARGET_CURRENT_PERCENT 7

#define ASSIST_LEVEL_STANDARD_2_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_STANDARD_2_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_STANDARD_2_MAX_SPEED_PERCENT	72
#define ASSIST_LEVEL_STANDARD_2_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_STANDARD_2_TARGET_CURRENT_PERCENT 10

#define ASSIST_LEVEL_STANDARD_3_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_STANDARD_3_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_STANDARD_3_MAX_SPEED_PERCENT	88
#define ASSIST_LEVEL_STANDARD_3_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_STANDARD_3_TARGET_CURRENT_PERCENT 14

#define ASSIST_LEVEL_STANDARD_4_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_STANDARD_4_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_STANDARD_4_MAX_SPEED_PERCENT	88
#define ASSIST_LEVEL_STANDARD_4_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_STANDARD_4_TARGET_CURRENT_PERCENT 19

#define ASSIST_LEVEL_STANDARD_5_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_STANDARD_5_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_STANDARD_5_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_STANDARD_5_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_STANDARD_5_TARGET_CURRENT_PERCENT 26

#define ASSIST_LEVEL_STANDARD_6_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_STANDARD_6_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_STANDARD_6_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_STANDARD_6_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_STANDARD_6_TARGET_CURRENT_PERCENT 36

#define ASSIST_LEVEL_STANDARD_7_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_STANDARD_7_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_STANDARD_7_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_STANDARD_7_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_STANDARD_7_TARGET_CURRENT_PERCENT 50

#define ASSIST_LEVEL_STANDARD_8_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_STANDARD_8_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_STANDARD_8_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_STANDARD_8_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_STANDARD_8_TARGET_CURRENT_PERCENT 70

#define ASSIST_LEVEL_STANDARD_9_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_STANDARD_9_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_STANDARD_9_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_STANDARD_9_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_STANDARD_9_TARGET_CURRENT_PERCENT 98

#define ASSIST_LEVEL_SPORT_0_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_SPORT_0_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_SPORT_0_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_SPORT_0_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_SPORT_0_TARGET_CURRENT_PERCENT 0

#define ASSIST_LEVEL_SPORT_1_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_SPORT_1_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_SPORT_1_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_SPORT_1_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_SPORT_1_TARGET_CURRENT_PERCENT 7

#define ASSIST_LEVEL_SPORT_2_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_SPORT_2_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_SPORT_2_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_SPORT_2_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_SPORT_2_TARGET_CURRENT_PERCENT 10

#define ASSIST_LEVEL_SPORT_3_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_SPORT_3_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_SPORT_3_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_SPORT_3_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_SPORT_3_TARGET_CURRENT_PERCENT 14

#define ASSIST_LEVEL_SPORT_4_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_SPORT_4_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_SPORT_4_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_SPORT_4_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_SPORT_4_TARGET_CURRENT_PERCENT 19

#define ASSIST_LEVEL_SPORT_5_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_SPORT_5_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_SPORT_5_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_SPORT_5_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_SPORT_5_TARGET_CURRENT_PERCENT 26

#define ASSIST_LEVEL_SPORT_6_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_SPORT_6_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_SPORT_6_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_SPORT_6_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_SPORT_6_TARGET_CURRENT_PERCENT 36

#define ASSIST_LEVEL_SPORT_7_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_SPORT_7_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_SPORT_7_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_SPORT_7_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_SPORT_7_TARGET_CURRENT_PERCENT 50

#define ASSIST_LEVEL_SPORT_8_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_SPORT_8_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_SPORT_8_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_SPORT_8_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_SPORT_8_TARGET_CURRENT_PERCENT 70

#define ASSIST_LEVEL_SPORT_9_FLAGS	ASSIST_FLAG_PAS | ASSIST_FLAG_THROTTLE
#define ASSIST_LEVEL_SPORT_9_MAX_CADENCE_PERCENT	100
#define ASSIST_LEVEL_SPORT_9_MAX_SPEED_PERCENT	100
#define ASSIST_LEVEL_SPORT_9_MAX_THROTTLE_CURRENT_PERCENT	100
#define ASSIST_LEVEL_SPORT_9_TARGET_CURRENT_PERCENT 98

#define ADC_VOLTAGE_CALIBRATION_STEPS_X100 0

// Unsafe configuration. Changing these makes your voided warranty even more void.

// Applied to both motor and controller temperature sensor
#define MAX_TEMPERATURE							85

// Current ramp down starts at MAX_TEMPERATURE - 5.
#define MAX_TEMPERATURE_RAMP_DOWN_INTERVAL		5

// Maximum allowed motor current in percent of maximum configured current (A)
// to still apply when maximum temperature has been reached.
// Motor current is ramped down linearly until this value when approaching
// max temperature.
#define MAX_TEMPERATURE_LOW_CURRENT_PERCENT		20

// Select battery percent mapping
#define BATTERY_PERCENT_MAP						BATTERY_PERCENT_MAP_NONE

// Time with no motor load until battery voltage is updated to avoid voltage sag.
#define BATTERY_NO_LOAD_DELAY_MS				2000

// Padding values for voltage range of battery.
#define BATTERY_FULL_OFFSET_PERCENT				8
#define BATTERY_EMPTY_OFFSET_PERCENT			8

// Battery SOC percentage when current ramp down starts.
#define LVC_RAMP_DOWN_OFFSET_PERCENT			10

// Maximum allowed motor current in percent of maximum configured current (A)
// to still apply when 0% battery has been reached.
// Motor current is ramped down linearly until this value when approaching "empty".
#define LVC_LOW_CURRENT_PERCENT					20

// Size of speed limit ramp down interval.
// If max speed is 50 and this is set to 3 then the
// target current will start ramping down when passing 47
// and be at 50% of assist target current when reaching 50.
#define SPEED_LIMIT_RAMP_DOWN_INTERVAL_KPH		3

// Current ramp down (e.g. when releasing throttle, stop pedaling etc.) in percent per 10 millisecond.
// Specifying 1 will make ramp down periond 1 second if releasing from full throttle.
// Set to 100 to disable
#define CURRENT_RAMP_DOWN_PERCENT_10MS			5

// Target speed in km/h when walk mode is engaged
#define WALK_MODE_SPEED_KPH						4

#define THROTTLE_RESPONSE_CURVE					THROTTLE_RESPONSE_CUSTOM

// This value is used when assist level is configured with throttle cadence
// override flag in config tool. Default is 100%.
#define THROTTLE_CADENCE_OVERRIDE_PERCENT		100

#endif
